export const PG_ERROR_CODES = {
  CANNOT_DELETE_LAST_ORGANIZER: 'ACS01',
  CATEGORY_IN_USE: 'ACS02',
  PROTECTED_CATEGORY: 'ACS03',
  DUPLICATE_RACE_COMBINATION: 'ACS04',
  DUPLICATE_CATEGORY_NAME: 'ACS05',
  INVALID_CATEGORY_SCOPE: 'ACS06',
  EVENT_HAS_RESULTS: 'ACS07',
  INVALID_EVENT_TRANSITION: 'ACS08'
} as const;

export type PgErrorCode = (typeof PG_ERROR_CODES)[keyof typeof PG_ERROR_CODES];
